export const { USER_REPO, ROLE_REPO } = {
  USER_REPO: 'USER_REPO',
  ROLE_REPO: 'ROLE_REPO',
};

export const { ADMIN_ROLE, READER_ROLE, AUTHOR_ROLE } = {
  ADMIN_ROLE: 'ADMIN',
  READER_ROLE: 'READER',
  AUTHOR_ROLE: 'AUTHOR',
};
