export const {
  IMAGE_S3_FOLDER,
  MEDIA_IMAGE_TYPE,
  USER_PROFILE_IMAGE_PATH,
  USER_PROFILE_IMAGE,
} = {
  IMAGE_S3_FOLDER: 'images',
  MEDIA_IMAGE_TYPE: 'image',
  USER_PROFILE_IMAGE_PATH: 'users/images',
  USER_PROFILE_IMAGE: 'PROFILE_IMAGE',
};
